######################################################################
# Automatically generated by qmake (2.01a) Fri Apr 2 10:10:34 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += systray_widget.h traffic_parser.h
SOURCES += main.cpp systray_widget.cpp traffic_parser.cpp
RESOURCES += networkled.qrc
